// backend/backfillReportValidation.js
//
// Pure validation for a backfill dry-run report BEFORE it's trusted as
// input to the write phase. No I/O, no network, no database access —
// safe and fast to run before ever touching a live row, and directly
// unit-testable.

const { US_ELIGIBLE_STATE_CODES } = require("./jobEligibility");

// Single source of truth for FIPS -> state/DC/territory abbreviation,
// shared between this validator and backend/scripts/backfillJobStates.js
// so the two can never disagree about what a given FIPS code means.
const FIPS_TO_ABBR = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT",
  "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI", "16": "ID", "17": "IL",
  "18": "IN", "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME", "24": "MD",
  "25": "MA", "26": "MI", "27": "MN", "28": "MS", "29": "MO", "30": "MT", "31": "NE",
  "32": "NV", "33": "NH", "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
  "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA", "54": "WV",
  "55": "WI", "56": "WY", "60": "AS", "66": "GU", "69": "MP", "72": "PR", "78": "VI",
};

/**
 * Validates a parsed backfill dry-run report object. Returns
 * { valid: true } or { valid: false, errors: [...] } — never throws.
 *
 * Checks:
 *   - report.mode === "dry-run" (never accept a report generated by
 *     write or rollback mode as write-phase input)
 *   - report.entries is an array of well-formed entries
 *   - every entry has a job_id, and every job_id is unique across the
 *     report (a duplicate would risk applying the same row twice, or
 *     masking a data problem in how the report was generated)
 *   - every entry with a proposed_state has a value that's actually in
 *     the US_ELIGIBLE_STATE_CODES allowlist (never trust an arbitrary
 *     string blindly)
 *   - every entry with a proposed_state also has a matched_fips that
 *     actually maps to that same state code (catches a report that's
 *     been hand-edited or corrupted inconsistently)
 */
function validateDryRunReport(report) {
  const errors = [];

  if (!report || typeof report !== "object") {
    return { valid: false, errors: ["report is not an object"] };
  }
  if (report.mode !== "dry-run") {
    errors.push(`expected report.mode === "dry-run", got ${JSON.stringify(report.mode)}`);
  }
  if (!Array.isArray(report.entries)) {
    errors.push("report.entries is not an array");
    return { valid: false, errors };
  }

  const seenIds = new Set();
  report.entries.forEach((entry, i) => {
    if (!entry || typeof entry !== "object") {
      errors.push(`entry ${i} is not an object`);
      return;
    }
    if (!entry.job_id || typeof entry.job_id !== "string") {
      errors.push(`entry ${i} is missing a valid job_id`);
    } else if (seenIds.has(entry.job_id)) {
      errors.push(`duplicate job_id "${entry.job_id}" at entry ${i}`);
    } else {
      seenIds.add(entry.job_id);
    }

    if (entry.proposed_state != null) {
      if (!US_ELIGIBLE_STATE_CODES.has(entry.proposed_state)) {
        errors.push(`entry ${i} (${entry.job_id}) has an invalid proposed_state: ${JSON.stringify(entry.proposed_state)}`);
      }
      if (entry.matched_fips == null) {
        errors.push(`entry ${i} (${entry.job_id}) has a proposed_state but no matched_fips`);
      } else if (FIPS_TO_ABBR[entry.matched_fips] !== entry.proposed_state) {
        errors.push(`entry ${i} (${entry.job_id}) proposed_state ${entry.proposed_state} does not match FIPS ${entry.matched_fips} (expected ${FIPS_TO_ABBR[entry.matched_fips]})`);
      }
    }
  });

  return { valid: errors.length === 0, errors };
}

module.exports = { validateDryRunReport, FIPS_TO_ABBR };
