const {deduplicate,CATEGORIES,createInventoryLoader}=require('./seoInventory');
const {isUsEligibleJob}=require('./jobEligibility');
const {classify}=require('../public/rook-job-classification');
const {publicPreview}=require('./pretrialProjection');
const definitions=[
 ['abbott','Abbott','abbott.svg',['Medical devices','Diagnostics','Nutrition','Medicines'],'https://www.abbott.com/en-us/products-solutions',
 'Abbott develops healthcare products across medical devices, diagnostic testing, nutrition and medicines. Its device areas include cardiovascular care, diabetes management, and technologies for pain and movement disorders. Diagnostic products support testing in hospitals, laboratories, blood banks and clinics. Its nutrition portfolio includes products for adults, children and infants. These business areas describe the company as a whole; the product focus and customer responsibilities of a specific sales position depend on the employer listing.'],
 ['medtronic','Medtronic','medtronic.svg',['Cardiovascular devices','Medical surgical technology','Neuroscience'],'https://www.medtronic.com/en-ca/our-company/key-facts.html',
 'Medtronic develops medical technology used to treat a range of health conditions. Its business areas include cardiovascular care, medical surgical technology and neuroscience. Cardiovascular products support care involving the heart and blood vessels, while other technologies are used in surgical procedures and neurological care. The company’s portfolio brings together devices, therapies and supporting services. These broad areas provide context for exploring sales opportunities; individual positions have their own product responsibilities, territory requirements and customer groups.'],
 ['stryker','Stryker','stryker.svg',['Medical and surgical equipment','Neurotechnology','Orthopaedics'],'https://www.stryker.com/us/en/about.html',
 'Stryker develops medical technologies, products and services across medical and surgical equipment, neurotechnology and orthopaedics. Its portfolio supports healthcare professionals working in surgical and other clinical settings. These businesses involve different products and customer needs, so a sales role in one division can have a different focus from a role in another. The current ROOK inventory below shows the categories represented in available listings. Check each full employer listing for the specific product area, account responsibilities and territory.'],
 ['abbvie','AbbVie','abbvie.svg',['Pharmaceuticals','Immunology','Oncology','Neuroscience','Eye care','Medical aesthetics'],'https://www.abbvie.com/science.html',
 'AbbVie is a biopharmaceutical company that researches and develops medicines and related healthcare products. Its research areas include immunology, oncology, neuroscience, eye care and medical aesthetics. Its work spans therapies for different diseases as well as products and technologies used in aesthetic medicine. Those areas describe the wider company rather than the scope of every opening. Pharmaceutical and account-focused opportunities may have different therapeutic responsibilities; review the current listing for its customer group, territory and experience requirements.'],
 ['johnson-and-johnson','Johnson & Johnson','johnson-and-johnson.svg',['Innovative medicine','Medical technology'],'https://www.jnj.com/',
 'Johnson & Johnson operates healthcare businesses in innovative medicine and medical technology. Its medicine areas include oncology, immunology, neuroscience and cardiopulmonary care. Its MedTech business develops technologies used by healthcare professionals in clinical care. The two businesses involve different products and customer relationships, making the division and product area important context when reviewing a sales opportunity. ROOK’s current job categories below are derived from available listings, while the full employer description explains each position’s responsibilities and requirements.'],
 ['philips','Philips','philips.webp',['Imaging','Image-guided therapy','Patient monitoring','Clinical informatics','Personal health'],'https://www.philips.com/a-w/about/innovation.html',
 'Philips is a health technology company with products and solutions for healthcare professionals and personal health. Its innovation areas include imaging, interventional technology, patient monitoring, clinical informatics and personal health. These areas support different stages of care and different healthcare workflows. Commercial opportunities can therefore vary by product portfolio and customer setting. The business areas listed here describe the wider company; use the current ROOK listings to identify available categories and consult each full description for role-specific details.'],
 ['ge-healthcare','GE HealthCare','ge-healthcare.svg',['Imaging','Ultrasound','Patient care solutions','Pharmaceutical diagnostics'],'https://www.gehealthcare.com/en-us/products',
 'GE HealthCare develops healthcare technology used in diagnosis, treatment and patient monitoring. Its product portfolio includes imaging systems, ultrasound, patient care solutions and pharmaceutical diagnostics. Patient care products include monitoring and anesthesia solutions, while pharmaceutical diagnostics include imaging agents. These areas serve different clinical needs and involve different purchasing and support processes. The current ROOK inventory shows which categories are represented in available openings. A specific sales position’s equipment portfolio, customer responsibilities and territory are defined by its employer listing.'],
 ['iqvia','IQVIA','iqvia.svg',['Clinical research services','Life sciences analytics','Healthcare technology','Commercial solutions'],'https://www.iqvia.com/about-us',
 'IQVIA provides clinical research services, analytics and technology solutions for the life sciences industry. Its work connects healthcare data, technology and industry expertise to support research and commercial activities. Its broader solutions include tools and services for clinical trials and commercial operations. IQVIA is a service and technology provider rather than a single pharmaceutical product manufacturer. When exploring its opportunities, review the full listing to understand the client context, business area, commercial responsibilities and any territory requirements.'],
 ['gsk','GSK',null,['Specialty medicines','General medicines','Vaccines'],'https://us.gsk.com/en-us/company/purpose-strategy-and-culture/',
 'GSK is a biopharmaceutical company developing medicines and vaccines. Its therapeutic focus includes respiratory, immunology and inflammation, oncology, HIV, and infectious diseases. Its portfolio combines specialty medicines, general medicines and vaccines, with products serving different patient needs and healthcare settings. These areas describe the company broadly and do not imply that every current opening covers all of them. The categories below reflect ROOK’s current inventory; each full employer listing identifies its product focus, customer group and responsibilities.'],
 ['viatris','Viatris','viatris.svg',['Branded medicines','Generic medicines','Complex and branded generics'],'https://www.viatris.com/en/Products',
 'Viatris is a healthcare company with a portfolio of branded medicines and generic medicines, including complex and branded generics. Its products span a variety of therapeutic areas. The company combines pharmaceutical, scientific and manufacturing capabilities to supply medicines in different markets. Product availability and the scope of a commercial position depend on the market and listing. The current ROOK opportunities below show the categories represented in available US-eligible jobs; consult the full employer description for the particular role and territory.'
 ]
];
const COMPANIES=Object.fromEntries(definitions.map(([slug,name,logo,areas,source,overview])=>[slug,{slug,name,logo,areas,source,overview}]));
const nameKey=n=>String(n||'').trim().replace(/\s+/g,' ').toLowerCase();
const searchUrl=c=>'/rook-search.html?company='+encodeURIComponent(c.name);
function buildCompanies(rows){
 const eligible=rows.filter(j=>j.status==='active'&&j.moderation_status==='approved'&&isUsEligibleJob(j));
 const groups=deduplicate(eligible);
 return Object.fromEntries(Object.values(COMPANIES).map(c=>{
  const entries=[];
  for(const group of groups){const matching=group.filter(j=>nameKey(j.company_name)===nameKey(c.name));if(!matching.length)continue;
   matching.sort((a,b)=>(Date.parse(b.date_posted)||0)-(Date.parse(a.date_posted)||0)||String(a.id).localeCompare(String(b.id)));
   const j=matching[0];if(!/^[a-f\d]{8}(?:-[a-f\d]{4}){3}-[a-f\d]{12}$/i.test(j.id))continue;
   // Only existing safe preview fields cross the public boundary.
   let preview;const safe=()=>preview||(preview=publicPreview(j));entries.push({url:'/jobs/'+j.id,get title(){return safe().title;},get location(){return safe().location;},labels:classify(j).labels});
  }
  const labels=[...new Set(entries.flatMap(j=>j.labels))].sort();
  return [c.slug,{...c,count:entries.length,entries,labels,qualified:entries.length>=20,
   categories:Object.entries(CATEGORIES).filter(([,category])=>category.labels.length&&entries.some(j=>j.labels.some(l=>category.labels.includes(l))&&(!category.human||!j.labels.includes('Veterinary')))).map(([slug,category])=>({slug,label:category.label}))}];
 }));
}
function createCompanyLoader(db,options={}){return createInventoryLoader(db,{...options,build:buildCompanies});}
const STYLES='<style>.company-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.company-card{background:white;border:1px solid var(--border);padding:20px;border-radius:14px;overflow-wrap:anywhere}.company-card h2{font-size:20px;margin:10px 0}.company-logo{position:relative;display:inline-flex;align-items:center;justify-content:center;width:48px;height:48px;background:white;border:1px solid #d7e0eb;border-radius:8px;color:#244e82;font-size:23px;font-weight:800;overflow:hidden}.company-logo img{position:absolute;inset:0;margin:auto;max-width:44px;max-height:44px;width:auto;height:auto;object-fit:contain;background:white}.company-copy{line-height:1.75;margin:18px 0}.company-links{display:flex;flex-wrap:wrap;gap:12px;margin:18px 0}.company-links a,.company-copy a{color:var(--royal);text-decoration:underline}.company-copy ul{padding-left:22px}.company-breadcrumb{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:24px}@media(max-width:600px){.company-grid{grid-template-columns:1fr}.company-logo{width:44px;height:44px}.company-logo img{max-width:40px;max-height:40px}}</style>';
function createCompanyHandlers({loadCompanies,pageShell,escapeHtml:e,baseUrl}){
 const logo=c=>`<span class="company-logo" aria-hidden="true">${e(c.name[0])}${c.logo?`<img src="/assets/employer-logos/${c.logo}" alt="" loading="lazy" onerror="this.remove()">`:''}</span>`;
 const fail=res=>res.status(503).set('Retry-After','60').send('Company inventory temporarily unavailable. Please try again shortly.');
 const crumbs=(items)=>`<nav class="company-breadcrumb" aria-label="Breadcrumb">${items.map((c,i)=>i===items.length-1?`<span aria-current="page">${e(c.name)}</span>`:`<a href="${e(c.url)}">${e(c.name)}</a><span aria-hidden="true">›</span>`).join('')}</nav>`;
 const breadcrumbSchema=items=>({'@type':'BreadcrumbList',itemListElement:items.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:baseUrl+c.url}))});
 return {
  directory:async(req,res)=>{try{
   const all=Object.values(await loadCompanies()).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));
   const canonicalUrl=baseUrl+'/companies',items=[{name:'Home',url:'/'},{name:'Companies',url:'/companies'}];
   const description='Explore current ROOK opportunities at ten featured healthcare employers. Compare eligible job counts and browse company sales pages.';
   const bodyHtml=STYLES+crumbs(items)+'<h1>Healthcare companies hiring on ROOK</h1><p class="company-copy">Explore ten featured employers from ROOK’s existing company ranking, ordered by current job count. Counts cover distinct active, approved US-eligible listings and can change. This first release features ten company pages.</p><div class="company-grid">'+all.map(c=>`<article class="company-card">${logo(c)}<h2>${e(c.name)}</h2><p data-company="${c.slug}" data-job-count="${c.count}">${c.count} current ROOK jobs</p><p class="company-copy">${e(c.labels.join(' · ')||'No current category inventory')}</p><nav class="company-links"><a href="/companies/${c.slug}">View company</a><a data-company-search="${e(c.name)}" href="${searchUrl(c)}">View jobs</a></nav></article>`).join('')+'</div>';
   return res.send(pageShell({title:'Healthcare Company Sales Jobs | ROOK',description,canonicalUrl,bodyHtml,publicCompany:true,noindex:all.reduce((n,c)=>n+c.count,0)<20||all.filter(c=>c.count>0).length<3||Object.keys(req.query).some(k=>!/^utm_|^(gclid|fbclid|ref)$/.test(k)),jsonLd:{'@context':'https://schema.org','@graph':[{'@type':'CollectionPage',url:canonicalUrl,name:'Healthcare companies hiring on ROOK',mainEntity:{'@type':'ItemList',numberOfItems:all.length,itemListElement:all.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,url:baseUrl+'/companies/'+c.slug}))}},breadcrumbSchema(items)]}}));
  }catch{return fail(res);}},
  employer:async(req,res)=>{if(!Object.hasOwn(COMPANIES,req.params.slug))return res.status(404).send('Company page not found.');try{
   const all=await loadCompanies(),c=all[req.params.slug],canonicalUrl=baseUrl+'/companies/'+c.slug;
   const items=[{name:'Home',url:'/'},{name:'Companies',url:'/companies'},{name:c.name,url:'/companies/'+c.slug}];
   const description=`Explore ${c.name} sales opportunities on ROOK: ${c.count} current eligible jobs. Learn about its business areas and open an employer-filtered job search.`;
   const related=Object.values(all).filter(x=>x.slug!==c.slug&&x.areas.some(a=>c.areas.includes(a))).slice(0,3);
   const bodyHtml=STYLES+crumbs(items)+logo(c)+`<h1>${e(c.name)} Sales Jobs</h1><section class="company-copy"><h2>About ${e(c.name)}</h2><p>${e(c.overview)}</p><p><a href="${e(c.source)}" rel="noopener">Official company information</a></p><h2>Products and business areas</h2><ul>${c.areas.map(a=>'<li>'+e(a)+'</li>').join('')}</ul></section><section class="company-copy"><h2>Current ROOK opportunities</h2><p data-job-count="${c.count}">${c.count} current active, approved US-eligible jobs on ROOK.</p><p>${c.count?e('Current categories: '+(c.labels.join(', ')||'Category information unavailable')):'There are no current ROOK openings for this employer. Browse related categories for other opportunities.'}</p><p>Availability can change. Counts use a cache of up to one minute. Full listing details and application links follow ROOK’s existing access requirements.</p><a class="btn btn-primary" data-company-search="${e(c.name)}" href="${searchUrl(c)}">View all ${e(c.name)} jobs</a></section>${c.entries.length?`<section class="company-copy"><h2>Current job previews</h2>${c.entries.slice(0,6).map(j=>`<article class="company-card"><h3><a href="${j.url}">${e(j.title)}</a></h3>${j.location?'<p>'+e(j.location)+'</p>':''}<a href="${j.url}">View job preview</a></article>`).join('')}</section>`:''}<nav class="company-links" aria-label="Related categories">${c.categories.map(x=>`<a href="/jobs/category/${x.slug}">${e(x.label)}</a>`).join('')||'<a href="/jobs/category/medical-sales-jobs">Medical Sales Jobs</a>'}</nav><nav class="company-links" aria-label="Company navigation"><a href="/companies">All featured companies</a>${related.map(x=>`<a href="/companies/${x.slug}">${e(x.name)}</a>`).join('')}</nav>`;
   return res.send(pageShell({title:c.name+' Sales Jobs | ROOK',description,canonicalUrl,bodyHtml,publicCompany:true,noindex:!c.qualified||Object.keys(req.query).some(k=>!/^utm_|^(gclid|fbclid|ref)$/.test(k)),jsonLd:{'@context':'https://schema.org','@graph':[{'@type':'CollectionPage',url:canonicalUrl,name:c.name+' Sales Jobs',about:{'@type':'Organization',name:c.name,url:c.source,...(c.logo?{logo:baseUrl+'/assets/employer-logos/'+c.logo}:{})},mainEntity:{'@type':'ItemList',numberOfItems:Math.min(6,c.count),itemListElement:c.entries.slice(0,6).map((j,i)=>({'@type':'ListItem',position:i+1,url:baseUrl+j.url,name:j.title}))}},breadcrumbSchema(items)]}}));
  }catch{return fail(res);}}
 };
}
module.exports={COMPANIES,nameKey,searchUrl,buildCompanies,createCompanyLoader,createCompanyHandlers};
