// Local-only browser measurement. Real routes/scorer; synthetic inventory and
// delayed in-memory database. Never supplies production credentials or services.
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const root=process.env.ROOK_TEST_ROOT || path.resolve(__dirname,'..');
const {chromium}=require(process.env.ROOK_PLAYWRIGHT_MODULE || 'playwright');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const jobs=Array.from({length:1100},(_,i)=>({id:`job-${String(i).padStart(5,'0')}`,title_original:'Territory Sales Representative',company_name:'PRIVATE Employer',source_url:'https://private.invalid',application_url:'https://private.invalid',location_raw:'Boston, MA',state:'MA',city:'Boston',job_lat:42.36+(i%10)*.04,job_lng:-71.06,status:'active',moderation_status:'approved',ai_analysis:{product_categories:['Medical Device','Veterinary']},experience_min_years:i%8,date_posted:'2026-09-24'}));
const tables={jobs,onboarding_v7_sessions:[],candidate_profiles:[]};let pages=0;const requests=[];
class Query {
 constructor(name){this.name=name;this.filters=[];this.kind='select';}
 select(){return this;}eq(k,v){this.filters.push(r=>r[k]===v);return this;}is(k,v){this.filters.push(r=>(r[k]??null)===v);return this;}
 gt(k,v){this.filters.push(r=>r[k]>v);return this;}lt(k,v){this.filters.push(r=>r[k]<v);return this;}order(){return this;}limit(){return this;}
 or(){return this;}range(a,b){this.rangeBounds=[a,b];return this;}
 insert(v){this.kind='insert';this.payload={created_at:new Date().toISOString(),...v};return this;}update(v){this.kind='update';this.payload=v;return this;}maybeSingle(){this.single=true;return this;}
 then(resolve,reject){return (async()=>{await delay(this.name==='jobs'?120:35);if(this.name==='jobs')pages++;let rows=tables[this.name];let found=rows.filter(r=>this.filters.every(f=>f(r)));if(this.kind==='insert'){rows.push(this.payload);found=[this.payload];}if(this.kind==='update')found.forEach(r=>Object.assign(r,this.payload));if(this.rangeBounds)found=found.slice(this.rangeBounds[0],this.rangeBounds[1]+1);return {data:structuredClone(this.single?found[0]||null:found),error:null};})().then(resolve,reject);}
}
const db={from:n=>new Query(n),auth:{getUser:async()=>({data:{user:null}})},rpc:async()=>({error:null})};
process.env.SUPABASE_URL='https://test.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='fake';
require.cache[require.resolve('@supabase/supabase-js')]={exports:{createClient:()=>db}};
const express=require('express');const app=express();app.use(express.json());app.use((req,res,next)=>{requests.push(req.method+' '+req.url);next();});app.use('/api/v7',async(req,res,next)=>{if(req.method==='POST'&&req.path==='/session'&&process.env.ROOK_TEST_SESSION_DELAY)await delay(Number(process.env.ROOK_TEST_SESSION_DELAY));next();},require(path.join(root,'backend/routes/onboardingV7')));app.get('/api/location-search',(req,res)=>res.json([{label:'Boston, MA',city:'Boston',state:'MA',zip:String(req.query.q)==='02109'?'02109':'02108',lat:String(req.query.q)==='02109'?42.37:42.36,lng:-71.06}]));if(process.env.ROOK_MANUAL_BROWSER) {
  app.get('/rook-config.js',(req,res)=>res.type('js').send("window.ROOK_CONFIG={SUPABASE_URL:'https://test.invalid',SUPABASE_ANON_KEY:'fake',API_BASE:'/api'};window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}})}})};"));
  app.get('/test-metrics',(req,res)=>res.json({pages,requests,profiles:tables.onboarding_v7_sessions.map(s=>s.profile)}));
  app.get(/\.html$/, (req,res,next)=>{
    const file=path.join(root,'public',path.basename(req.path));if(!fs.existsSync(file))return next();
    const monitor=`<script>if(location.pathname.includes('dashboard')){const probe=document.createElement('button');probe.textContent='Test exit intent';probe.style.cssText='position:fixed;right:4px;bottom:4px;z-index:9999';probe.onclick=()=>document.dispatchEvent(new MouseEvent('mouseout',{clientY:-1,relatedTarget:null}));document.body.append(probe);}document.addEventListener('click',e=>{if(e.target.id==='btnTerritoryNext')sessionStorage.setItem('test_clicked',Date.now())},true);let cards=null;function frame(){if(document.querySelector('main.main')&&!document.documentElement.dataset.clickToShell)document.documentElement.dataset.clickToShell=Date.now()-Number(sessionStorage.getItem('test_clicked'));const row=document.querySelector('#jobList .job-row');if(!cards && row && document.querySelector('#jobList').dataset.demo==='false' && row.getBoundingClientRect().height && row.getBoundingClientRect().top<innerHeight){cards=Date.now();document.documentElement.dataset.clickToCards=cards-Number(sessionStorage.getItem('test_clicked'));}if(cards && document.querySelector('dialog[open]') && !document.documentElement.dataset.cardsToPopup)document.documentElement.dataset.cardsToPopup=Date.now()-cards;requestAnimationFrame(frame)}requestAnimationFrame(frame);</script>`;
    res.send(fs.readFileSync(file,'utf8').replace(/<script[^>]*src=["']https:[\s\S]*?<\/script>/g,'')+monitor);
  });
}
app.use(express.static(path.join(root,'public')));
if(process.env.ROOK_MANUAL_BROWSER) {app.listen(Number(process.env.PORT||4318),'127.0.0.1',()=>console.log('LOCAL TEST SERVER '+(process.env.PORT||4318)));} else (async()=>{const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:process.env.ROOK_CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const results=[];
try {for(const mobile of [false,true]) {const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile,hasTouch:mobile});const errors=[];await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.href.includes('supabase')&&u.origin!==origin)return route.fulfill({contentType:'application/javascript',body:"window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}})}})}"});if(u.pathname==='/rook-config.js')return route.fulfill({contentType:'application/javascript',body:"window.ROOK_CONFIG={SUPABASE_URL:'https://test.invalid',SUPABASE_ANON_KEY:'fake',API_BASE:'/api'}"});if(u.origin!==origin)return route.fulfill({body:''});return route.continue();});
await context.addInitScript(()=>{window.paintMetrics={};document.addEventListener('click',e=>{if(e.target.id==='btnTerritoryNext')sessionStorage.setItem('test_clicked',Date.now());},true);function frame(){const row=document.querySelector('#jobList .job-row');if(row && document.querySelector('#jobList')?.dataset.demo==='false' && row.getBoundingClientRect().height && getComputedStyle(row).visibility!=='hidden'){window.paintMetrics.cards ||= Date.now();}if(document.querySelector('dialog[open]'))window.paintMetrics.popup ||= Date.now();requestAnimationFrame(frame);}requestAnimationFrame(frame);});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const startPages=pages,startRequests=requests.length;
await page.goto(origin+'/rook-onboarding-v7.html');await page.fill('#locationInput','02108');await page.click('.rlw-item');await page.click('#btnDetailsNext');await page.check('input[value="Medical Device"]');await page.click('#btnIndustryNext');await delay(650);await page.check('input[name="years"][value="5.5"]');await page.click('#btnYearsNext');await page.check('input[name="territory"][value="local"]');await page.click('#btnTerritoryNext');await page.waitForURL('**/rook-dashboard-v7.html');await page.waitForFunction(()=>window.paintMetrics.cards);await page.waitForFunction(()=>window.paintMetrics.popup);const metrics=await page.evaluate(()=>({clickToCards:paintMetrics.cards-Number(sessionStorage.getItem('test_clicked')),cardsToPopup:paintMetrics.popup-paintMetrics.cards}));assert(!(await page.locator('#jobList').innerText()).includes('PRIVATE'));assert.equal(await page.locator('#jobList .job-row').count(),20);await page.click('[data-skip]');assert.equal(await page.locator('dialog[open]').count(),0);assert(page.url().endsWith('rook-dashboard-v7.html'));await delay(10100);await page.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseout',{clientY:-1,relatedTarget:null})));await delay(100);assert.equal(await page.locator('dialog[open]').count(),mobile?0:1);if(!mobile)await page.click('[data-skip]');assert.deepEqual(errors,[]);if(process.env.ROOK_EXPECT_OPTIMIZED){assert(metrics.cardsToPopup>=2950,JSON.stringify(metrics));assert.equal(pages-startPages,3);}
results.push({device:mobile?'mobile':'desktop',...metrics,databaseJobPages:pages-startPages,apiRequests:requests.slice(startRequests).filter(s=>s.includes('/api/'))});if(process.env.ROOK_SCREENSHOT_DIR){fs.mkdirSync(process.env.ROOK_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.ROOK_SCREENSHOT_DIR,(mobile?'mobile':'desktop')+'.png'),fullPage:true});}await context.close();}
console.log(JSON.stringify({inventory:'1100 synthetic jobs; real scorer, routes and UI; database delay 120ms/page, 35ms/session operation',results},null,2));}finally{await browser.close();server.close();server.closeAllConnections();}})().catch(e=>{console.error(e);process.exitCode=1;});
