const assert=require('node:assert/strict'),{createRequire}=require('module');
const req=createRequire(__filename);const {scoreJob}=req('./matching');const m={exports:req('./v7Matching')};
const p={home_lat:28.9,home_lng:-82,home_state:'FL',desired_industries:['Medical Device'],territory_size_preferences:['local'],resume_structured:{industries_experience:[{industry:'Diagnostics'}],product_categories:['Diagnostics','Capital equipment'],customer_types:['Physicians','Community Health'],seniority_level:'Account Executive',sales_motion:['hunter','Field'],total_sales_years:15,performance_highlights:['Synthetic documented achievement']}};
function job(id,miles,medline=false){return {id,title_original:medline?'Physicians Office Sales Representative':'Physician Account Executive',company_name:medline?'Medline':'Quest Diagnostics',location_raw:'Apopka, FL',state:'FL',status:'active',moderation_status:'approved',job_lat:p.home_lat+miles/3958.8*180/Math.PI,job_lng:p.home_lng,location_evidence:{version:1,status:'validated',source_country_code:'US',source_location:'Apopka, FL'},ai_analysis:{product_categories:medline?['Capital equipment','Diagnostics']:['Diagnostics'],preferred_industries:medline?[]:['Diagnostics'],required_customer_types:[medline?'Community Health':'Physicians'],seniority_level:medline?'Territory Representative':'Account Executive',sales_motion:[medline?'Field':'hunter'],required_years_experience:medline?2:5}};}
function db(rows){const q={select(){return q},eq(){return q},or(){return q},order(){return q},range(a,b){return Promise.resolve({data:rows.slice(a,b+1)})}};return{from(){return q}};}
function smooth(preference,qualification,miles,kind='local'){if(kind!=='local')return Math.round(.7*preference+.3*qualification);const old=miles<=75?0:miles<=150?5:15;const pref=Math.round(preference+old-15*miles/300);return Math.round(.7*pref+.3*qualification);}
(async()=>{
 const quest=job('quest',37),miami=job('miami',245,true);const a=scoreJob(quest,p),b=scoreJob(miami,p);assert.deepEqual([a.candidate_fit,a.preference_fit,a.overall_score],[100,80,86]);assert.deepEqual([b.candidate_fit,b.preference_fit,b.overall_score],[100,85,90]);
 const before=await req('./v7Matching').rank(db([quest,miami]),p,['Diagnostics']);const after=await m.exports.rank(db([quest,miami]),p,['Diagnostics']);assert.deepEqual(Array.from(after,j=>j.id),['quest','miami']);assert.equal(after[0].match.overall_score,99);assert.equal(after[1].match.overall_score,92);assert.deepEqual([...before.map(j=>j.id)].sort(),Array.from(after,j=>j.id).sort());assert.deepEqual(p.desired_industries,['Medical Device']);
 for(const [city,lat,lng,state] of [['Oxford',28.9,-82,'FL'],['Boston',42.36,-71.06,'MA'],['Louisville',38.25,-85.76,'KY'],['San Francisco',37.77,-122.42,'CA']]){const profile={...p,home_lat:lat,home_lng:lng,home_state:state};const j={...quest,location_raw:city+', '+state,state,job_lat:lat,job_lng:lng,location_evidence:undefined};const r=await m.exports.rank(db([j]),profile,['Diagnostics']);assert.equal(r.length,1);assert.equal(r[0].match.overall_score,100);}
 const distances=[0,25,75,75.01,150,150.01,225,245,300];const scores=distances.map(d=>smooth(d<=75?100:d<=150?95:85,100,d));assert(scores.every((s,i)=>!i||scores[i-1]>=s));assert(smooth(85,100,245)>smooth(100,69,20));assert.equal(smooth(95,90,null,'territory'),Math.round(.7*95+.3*90));assert.equal(smooth(100,90,null,'remote_us'),97);assert.equal(smooth(100,90,null,'national_us'),97);
 assert.equal(smooth(80,100,37),85);assert.equal(smooth(85,100,245),92);assert.equal(smooth(100,100,37),99);
 const normal=await m.exports.rank(db([quest,miami]),p,[]);assert.equal(normal.find(j=>j.id==='quest').match.overall_score,85);
 const diag={...p,desired_industries:['Diagnostics']};let previous=101;
 for(const miles of [0,1,25,74.99,75,75.01,100,149.99,150,150.01,200,225,245,299.99,300-1e-8]){const j=job('point',miles);const v=scoreJob(j,diag,{geography:{kind:'local'},smoothLocalDistance:true});const expected=Math.round(100-15*miles/300);assert.equal(v.preference_fit,expected);assert.equal(v.overall_score,Math.round(.7*expected+.3*v.candidate_fit));assert(v.overall_score<=previous);previous=v.overall_score;}
 for(const kind of ['territory','remote_us','national_us']){const j={...quest,job_lat:null,job_lng:null,location_raw:'United States'};assert.deepEqual(scoreJob(j,diag,{geography:{kind},smoothLocalDistance:true}),scoreJob(j,diag,{geography:{kind}}));}
 const onlyDiag={...job('z',20),ai_analysis:{...quest.ai_analysis,product_categories:['Diagnostics']}};const mixed={...job('a',20,true),ai_analysis:{...miami.ai_analysis,product_categories:['Diagnostics','Capital equipment']}};assert.equal((await m.exports.rank(db([mixed,onlyDiag]),p,['Diagnostics']))[0].id,'z');
 const strong=scoreJob(miami,diag,{geography:{kind:'local'},smoothLocalDistance:true});const weak=scoreJob(job('weak',20,true),{...diag,resume_structured:{...p.resume_structured,product_categories:['unrelated'],customer_types:['unrelated'],sales_motion:['unrelated']}},{geography:{kind:'local'},smoothLocalDistance:true});assert(strong.overall_score>weak.overall_score);
 console.log('Actual scorer stronger distant / weaker nearby:',strong.overall_score,weak.overall_score);
 console.log('PASS: production-derived 86/90 fixtures; Diagnostics selection alignment; eligible identity preservation; no profile mutation; four-city profiles; empty-selection fallback; continuous-distance monotonicity/boundaries; strong distant over weaker nearby; scope preservation.');
})();
