'use strict';
const { CATEGORIES, category } = require('./catalog');
const { origin } = require('../resources/catalog');
const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const publicCategories = () => CATEGORIES.filter(item => !['dental', 'product-launches'].includes(item.slug));
function label(slug) { return category(slug)?.label || String(slug || 'Industry News').replace(/-/g, ' '); }
function shell({ title, description, path, body, image, schema = null }) {
  const canonical = `${origin()}${path}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ROOK</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}">${image ? `<meta property="og:image" content="${esc(image)}"><meta name="twitter:card" content="summary_large_image">` : ''}${schema ? `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script>` : ''}<style>body{margin:0;color:#071e41;font:16px/1.65 Inter,Arial,sans-serif}a{color:#006aca}.wrap{max-width:1060px;margin:auto;padding:34px 22px}.hero{background:#071e41;color:white;padding:55px 0}.hero p{color:#9dc9f1}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.card{border:1px solid #dfe7ef;border-radius:10px;padding:22px}.card a{text-decoration:none}.meta{color:#60758b;font-size:14px}.article{max-width:760px}.article h1{font-size:clamp(2rem,5vw,3.4rem);line-height:1.08}.article h2{margin-top:34px}.sources{background:#f4f8fb;padding:20px;border-radius:8px;margin-top:36px}.cta{background:#071e41;color:white;padding:28px;border-radius:10px;margin:40px 0}.cta a{color:#43e7e9}.cats{display:flex;gap:10px;flex-wrap:wrap;margin:25px 0}</style></head><body>${body}</body></html>`;
}
function card(article) { return `<article class="card"><p class="meta">${esc(label(article.category))} · ${esc(new Date(article.published_at).toLocaleDateString('en-US'))}</p><h2><a href="/news/${esc(article.slug)}/">${esc(article.title)}</a></h2><p>${esc(article.description)}</p></article>`; }
function index(items = [], selected = null) {
  const title = selected ? label(selected) : 'Industry News';
  const path = selected ? `/news/${selected}/` : '/news/';
  const cats = publicCategories().map(item => `<a href="/news/${item.slug}/">${esc(item.label)}</a>`).join('');
  return shell({ title, description: 'Current medical, veterinary and life-sciences industry developments for sales professionals.', path, body: `<header class="hero"><div class="wrap"><p>ROOK CAREERS</p><h1>${esc(title)}</h1><p>Commercially relevant developments across medical, veterinary and life-sciences markets.</p></div></header><main class="wrap"><nav class="cats"><a href="/news/">All news</a>${cats}</nav><section class="grid">${items.map(card).join('') || '<p>No published stories yet.</p>'}</section></main>` });
}
function article(item, related = []) {
  const path = `/news/${item.slug}/`, canonical = `${origin()}${path}`, image = `${canonical}social.jpg`;
  const sources = (item.sources || []).map(source => `<li><a href="${esc(source.url)}" rel="nofollow noreferrer">${esc(source.publisher)}</a>${source.published_at ? ` — ${esc(new Date(source.published_at).toLocaleDateString('en-US'))}` : ''}</li>`).join('');
  const schema = { '@context': 'https://schema.org', '@type': 'NewsArticle', headline: item.title, description: item.description, datePublished: item.published_at, dateModified: item.updated_at || item.published_at, mainEntityOfPage: canonical, image: [image], publisher: { '@type': 'Organization', name: 'ROOK Careers', url: origin() } };
  const resourceCategory = ['medical-device','diagnostics-laboratory','pharmaceutical-biotech','veterinary-animal-health'].includes(item.category) ? item.category : 'industry-news';
  return shell({ title: item.title, description: item.description, path, image, schema, body: `<main class="wrap article"><p><a href="/news/">Industry News</a> / <a href="/news/${esc(item.category)}/">${esc(label(item.category))}</a></p><article><p class="meta">${esc(new Date(item.published_at).toLocaleDateString('en-US'))} · ${esc(label(item.category))}</p><h1>${esc(item.title)}</h1><p><strong>${esc(item.description)}</strong></p>${item.body_html}<p><a href="/resources/category/${resourceCategory}/">Explore related ROOK career guides →</a></p><section class="sources"><h2>Sources</h2><ul>${sources}</ul></section></article><aside class="cta"><h2>Find medical sales jobs matched to you</h2><p>Build your ROOK profile and discover matched medical and veterinary sales roles.</p><a href="/rook-onboarding-v8.html">Get started with ROOK →</a></aside>${related.length ? `<section><h2>Related industry news</h2><div class="grid">${related.map(card).join('')}</div></section>` : ''}</main>` });
}
function adminReport(report) { const rows = report.candidates.map(c => { const sources=(c.sources||[]).map(s=>`<a href="${esc(s.url)}" rel="noreferrer">${esc(s.name)}</a>${s.byline?` — By ${esc(s.byline)}`:''}`).join('<br>'); return `<tr><td>${esc(c.headline)}</td><td>${esc(c.category)}</td><td>${esc(c.eventType)}</td><td>${sources}</td><td>${esc(c.relevanceStatus)}</td></tr>`; }).join(''); return `<!doctype html><html><head><meta name="robots" content="noindex,nofollow"><title>Industry News candidate report</title></head><body><h1>Industry News candidate report</h1><pre>${esc(JSON.stringify(report.run?.metrics || {}, null, 2))}</pre><table><tr><th>Headline</th><th>Category</th><th>Event</th><th>Sources</th><th>Status</th></tr>${rows}</table></body></html>`; }
module.exports = { esc, shell, index, article, adminReport, publicCategories };
