const {CATEGORIES,category,origin,urlFor}=require('./catalog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'America/New_York'});
function cta(){return `<aside class="resource-cta"><span class="case-icon" aria-hidden="true">▣</span><h2>Looking for your next<br>sales opportunity?</h2><p>ROOK searches employer career sites to help you find medical and veterinary sales opportunities that fit your experience.</p><a class="button" data-resource-event="resource_find_matches_click" href="/rook-onboarding-v7.html">Find My Matches <span>→</span></a><a class="browse-link" data-resource-event="resource_job_click" href="/jobs">Browse All Jobs →</a></aside>`;}
function card(a,featured=false){return `<article class="article-card ${featured?'featured':''}"><a class="card-image" href="/resources/${esc(a.slug)}/"><img src="${esc(a.image_path)}" alt="${esc(a.image_alt)}" ${featured?'':'loading="lazy"'}>${featured?'<span class="feature-badge">FEATURED ARTICLE</span>':''}</a><div class="card-content"><a class="eyebrow" href="/resources/category/${esc(a.category)}/">${esc(category(a.category)?.label)}</a><h${featured?'2':'3'}><a href="/resources/${esc(a.slug)}/">${esc(a.title)}</a></h${featured?'2':'3'}>${featured?`<p class="excerpt">${esc(a.description)}</p>`:''}<div class="meta"><span>▦ ${date(a.published_at)}</span><span>◷ ${Math.max(1,Math.ceil(a.word_count/220))} min read</span></div><a class="read-link ${featured?'button':''}" href="/resources/${esc(a.slug)}/">Read Article <span>→</span></a></div></article>`;}
function shell({title,description,path,body,image='/assets/resources/hero.jpg',article,noindex=false}){
 const url=origin()+path;
 const structured=article?[
 {'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.description,image:origin()+image,datePublished:article.published_at,dateModified:article.updated_at,mainEntityOfPage:url,author:{'@type':'Organization',name:'ROOK',url:origin()},publisher:{'@type':'Organization',name:'ROOK',url:origin()}},
 {'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Resources',item:origin()+'/resources/'},{name:category(article.category).label,item:origin()+'/resources/category/'+article.category+'/'},{name:article.title,item:url}].map((x,i)=>({'@type':'ListItem',position:i+1,...x}))}]:null;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ROOK</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(url)}">${noindex?'<meta name="robots" content="noindex,follow">':''}<meta property="og:type" content="${article?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(url)}"><meta property="og:image" content="${esc(origin()+image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${esc(origin()+image)}">${article?`<meta property="article:published_time" content="${esc(article.published_at)}"><meta property="article:modified_time" content="${esc(article.updated_at)}">`:''}<link rel="icon" href="/assets/favicon.ico"><link rel="stylesheet" href="/resources.css"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">${structured?`<script type="application/ld+json">${JSON.stringify(structured).replace(/</g,'\\u003c')}</script>`:''}<script src="/rook-attribution.js"></script><script async src="https://www.googletagmanager.com/gtag/js?id=AW-18428232873"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','AW-18428232873');gtag('config','G-LDG2CL5Z8R');</script><script src="/resources.js" defer></script></head><body ${article?`data-resource-slug="${esc(article.slug)}"`:''}><a class="skip" href="#main">Skip to content</a><header><div class="nav-inner"><a href="/" aria-label="ROOK home"><img class="logo" src="/assets/rook-full-logo-480.png" alt="ROOK Medical & Veterinary Sales Jobs"></a><button class="menu-toggle" aria-controls="resource-nav" aria-expanded="false" aria-label="Open navigation">☰</button><nav id="resource-nav" aria-label="Main navigation"><a href="/">Home</a><a href="/jobs">Find Jobs</a><a data-resource-event="resource_find_matches_click" href="/rook-onboarding-v7.html">Find My Matches</a><a href="/rook-employers.html">Employers</a><a class="active" href="/resources/" aria-current="${article?'false':'page'}">Resources</a><a href="/rook-about.html">About</a><a class="button outline" href="/rook-login.html">Sign In</a><a class="button" data-resource-event="resource_find_matches_click" href="/rook-onboarding-v7.html">Get Started</a></nav></div></header><main id="main">${body}</main><footer><a href="/">ROOK</a><span>Medical & Veterinary Sales Jobs</span><a href="/rook-privacy.html">Privacy</a><a href="/rook-terms.html">Terms</a></footer></body></html>`;
}
function index({items,count,categorySlug,q='',page=1,all=false}){
 const c=category(categorySlug);const home=!c&&!q&&page===1&&!all;
 const title=c?c.label:q?'Search Career Resources':'ROOK Career Resources';
 const search=`<form role="search" action="${c?'/resources/category/'+c.slug+'/':'/resources/'}"><label class="sr-only" for="resource-search">Search articles, topics or keywords</label><span aria-hidden="true">⌕</span><input id="resource-search" name="q" value="${esc(q)}" placeholder="Search articles, topics or keywords..." maxlength="100"><button>Search</button></form>`;
 const categories=`<section class="categories" aria-label="Resource categories">${CATEGORIES.slice(0,7).map(c=>`<a class="category-card" href="/resources/category/${c.slug}/"><img src="/assets/resources/${c.image}.jpg" alt="" loading="lazy"><span>${esc(c.label==='Career Advice / Territory Sales'?'Career Advice':c.label)}<b>→</b></span></a>`).join('')}</section>`;
 const feature=home&&items.length?`<div class="section-heading mobile-feature-title"><h2>Featured Article</h2></div><div class="feature-grid">${card(items[0],true)}${cta()}</div>`:'';
 const shown=home?items.slice(1):items;
 const pageUrl=p=>`${c?'/resources/category/'+c.slug+'/':'/resources/'}?${new URLSearchParams({...q?{q}:{},page:p})}`;
 const body=`<section class="hero"><div class="hero-inner"><p class="hero-label">ROOK CAREER RESOURCES</p><h1>${home?'Insights for Medical &amp; <br>Veterinary Sales Professionals':esc(title)}</h1><p>Career guides, industry insights and practical advice to help you<br class="desktop-only"> build a successful career in medical, animal health and related sales.</p>${search}</div></section><div class="container">${categories}${feature}<section><div class="section-heading"><h2>${home?'Latest Articles':esc(title)}</h2>${home?'<a href="/resources/?page=1">View All Articles →</a>':''}</div><div class="article-grid">${shown.map(a=>card(a)).join('')}</div>${!items.length?'<div class="empty"><h2>Career resources are on the way</h2><p>Explore our categories or browse current sales opportunities.</p><a href="/jobs">Browse Jobs →</a></div>':''}<nav class="pagination" aria-label="Article pages">${page>1?`<a href="${esc(pageUrl(page-1))}">← Previous</a>`:''}${count>page*12?`<a href="${esc(pageUrl(page+1))}">Next →</a>`:''}</nav></section><section class="topics"><h2>Popular Topics</h2><div>${CATEGORIES.filter(c=>c.slug!=='industry-news').map(c=>`<a href="/resources/category/${c.slug}/">${esc(c.label)} →</a>`).join('')}<a href="/resources/?q=territory">Territory Management →</a></div></section></div>`;
 return shell({title,description:'Career guides, industry insights and practical advice for medical and veterinary sales professionals.',path:(c?'/resources/category/'+c.slug+'/':'/resources/')+(page>1?'?page='+page:''),body,noindex:!!q});
}
function article(a,related=[],jobs=[]){
 const c=category(a.category);
 const body=`<div class="container article-layout"><article class="article-body"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/resources/">Resources</a> / <a href="/resources/category/${c.slug}/">${esc(c.label)}</a></nav><p class="eyebrow">${esc(c.label)}</p><h1>${esc(a.title)}</h1><p class="dek">${esc(a.description)}</p><div class="meta"><span>By ROOK Career Resources</span><time datetime="${esc(a.published_at)}">${date(a.published_at)}</time><span>${Math.ceil(a.word_count/220)} min read</span></div><img class="article-hero" src="${esc(a.image_path)}" alt="${esc(a.image_alt)}"><div class="prose">${a.body_html}</div><p class="updated">Updated ${date(a.updated_at)}</p><section class="sources"><h2>Sources & further reading</h2><ul>${a.sources.map(s=>`<li><a href="${esc(s.url)}" rel="noopener noreferrer">${esc(s.title)}</a></li>`).join('')}</ul></section></article><div class="article-sidebar">${cta()}<section class="related-jobs"><h2>Explore ${esc(c.label)} opportunities</h2>${jobs.map(j=>`<a data-resource-event="resource_job_click" href="${esc(j.url)}">${esc(j.title)}<small>${esc(j.location)}</small> →</a>`).join('')}<a data-resource-event="resource_job_click" href="/jobs/category/${c.jobs}">View current job previews →</a></section></div></div>${related.length?`<section class="container"><h2>Related Articles</h2><div class="article-grid">${related.map(a=>card(a)).join('')}</div></section>`:''}`;
 return shell({title:a.title,description:a.description,path:'/resources/'+a.slug+'/',body,image:a.image_path,article:a});
}
module.exports={esc,index,article,shell};
